source: airflow

base_url: https://airflow.apache.org

seed_url: https://airflow.apache.org/docs/apache-airflow/stable/

allowed_paths:
  - /docs/apache-airflow/stable/core-concepts/
  - /docs/apache-airflow/stable/authoring-and-scheduling/
  - /docs/apache-airflow/stable/howto/
  - /docs/apache-airflow/stable/tutorial/
  - /docs/apache-airflow/stable/administration-and-deployment/
  - /docs/apache-airflow/stable/security/
  - /docs/apache-airflow/stable/configurations-ref/

max_pages: 100